---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: <%= ENV['AWS_REGION'] || 'ap-northeast-1' %>
  availability_zone: <%= ENV['AWS_AZ'] || 'ap-northeast-1c' %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids: <%= ENV['AWS_SG_IDS'].split(",") %>
  associate_public_ip: true

transport:
  ssh_key: <%= File.expand_path("~/.ssh/#{ENV['AWS_SSH_KEY_ID']}") %>
  username: <%= ENV['AWS_EC2_USER'] || 'ec2-user' %>

provisioner:
  name: shell

platforms:
  - name: amazon-2016.03.3
    driver:
      image_id: <%= ENV['AWS_EC2_AMI_ID'] || 'ami-374db956' %> # Tokyo
      instance_type: c3.large

suites:
  - name: default
    run_list:
    attributes:
