---
version: 2
jobs:
  build:
    docker:
      - image: amazonlinux:2017.03-with-sources
    working_directory: /root/rpmbuild
    steps:
      - checkout
      - run: ./ci/build_deps.sh
      - run: rpmbuild -ba SPECS/nginx.spec