---
version: 2
jobs:
  build:
    docker:
      - image: amazonlinux:2017.03-with-sources
    working_directory: /root/rpmbuild
    steps:
      - checkout
      - run: ./ci/build_deps.sh
      - run: rpmbuild -ba SPECS/nginx.spec
      - run: rpm -ivh RPMS/x86_64/nginx-*
      - run: cp -f ./ci/nginx.conf /etc/nginx/nginx.conf
      - run: nginx -t
      - run: service nginx start
      - run: curl -vf 127.0.0.1/hello
      - store_artifacts:
          path: /root/rpmbuild/RPMS