---
jobs:
  build:
    docker:
      - amazonlinux:2017.03-with-sources
    working_directory: /root/rpmbuild
    steps:
      - checkout
      - run: ./.circleci/depends.sh
      - run: rpmbuild -ba SPECS/nginx.spec